### ISSUE TITLE
anonymous view

### ISSUE THREAD

**Issue by adamjapon** [CaliAlec/ChromeIGStory#106]
i noticed that today the extension has new effect on the page.
kinda liked the previous version.

anyway, witth this new look, i cant find where the option to anonymous view is located?
can you guys give me hint/clue? (also if can, can you provide the option to keep in previous version?)

thanks

**Comment by CaliAlec** [comment]
@adamjapon The only reason the previous version had a toggle for "Anonymous View" is because Instagram implemented their own stories which marked the story as seen when you open it in their viewer, but now that Chrome IG Story completely replaces Instagram's implementation, it's anonymous by default since the extension don't mark the story as seen when you view it.
