### ISSUE TITLE
[Issue] Download doesn't work an overlay mode

### ISSUE THREAD

**Issue by anga83** [CaliAlec/ChromeIGStory#108]
Hi there!

Since yesterday (?) the download via the pop-up window doesn't work anymore (both version 2.1.7 and 2.2.1). The circle spins one ore two times but no zip file is downloading.

In full screen mode or on the Instagram website everything works as usual.

**Comment by nbmrjuhneibkr** [comment]
I can confirm this issue with ChromeIGStory 2.2.2. The only way to download story as .zip is to open ChromeIGStory in a separate window. This issue seems to be caused by the Chromium/Chrome 65 update.

**Comment by CaliAlec** [comment]
This is because Chrome 65 prevents FileSaver from downloading the zip file. (https://github.com/eligrey/FileSaver.js/issues/408)

I hotfixed this in v2.2.3 by adding 'save_link.target = "_blank";' to FileSaver.js in the node_modules folder, but I'm waiting for FileSaver to officially fix it by detecting Chrome extensions (https://github.com/eligrey/FileSaver.js/commit/e865e37af9f9947ddcced76b549e27dc45c1cb2e#diff-dc5eaddfec51693151d584d4cd59b0cfR160)
