### ISSUE TITLE
Why cant anything be downloaded?

### ISSUE THREAD

**Issue by happycheeseburger** [CaliAlec/ChromeIGStory#121]
Before you could download stories but that feature doesnt work any more is it or will it be fixed?

**Comment by roonieone** [comment]
It seems that you're only able to download stories when you've "popped-out" the window, but this should be fixed so you can download without "popping-out," if possible.

**Comment by CaliAlec** [comment]
This is because Chrome 65 prevents FileSaver from downloading the zip file. (https://github.com/eligrey/FileSaver.js/issues/408)

I hotfixed this in v2.2.3 by adding 'save_link.target = "_blank";' to FileSaver.js in the node_modules folder, but I'm waiting for FileSaver to officially fix it by detecting Chrome extensions (https://github.com/eligrey/FileSaver.js/commit/e865e37af9f9947ddcced76b549e27dc45c1cb2e#diff-dc5eaddfec51693151d584d4cd59b0cfR160)
