### ISSUE TITLE
can not use 

### ISSUE THREAD

**Issue by nicknaumik** [CaliAlec/ChromeIGStory#147]
i'm logged in  but  this popsup
There was a problem with your Instagram session.

Make sure you are signed into Instagram and try again.

**Comment by furroy** [comment]
it's been totally dead for a week or two now. i shame i used it all the time.

**Comment by viohug** [comment]
don't know what the heck are you talking about guys

Apparently it updated automatically for me some days ago and works, with 4 options of video now
Yesterday there was only one option and not the bigger, maybe that was something instagram did because there was a lot of traffic, 
Righ now the 4 sizes are back, see? https://images2.imgbox.com/13/b9/ZQ6J7ang_o.png

**Comment by Alex220** [comment]
@nicknaumik
Try Disable "Anonymous viewing enabled" to solve the problem.

**Comment by Alex220** [comment]
@furroy
this extension Works perfectly for me.
ChromeIGStory is the best extension to watch Instagram's live and story.

**Comment by Alex220** [comment]
> Yesterday there was only one option and not the bigger, maybe that was something instagram did because there was a lot of traffic.
@viohug Yes. It was probably Instagram's decision!
