### ISSUE TITLE
Why is the background page in persistent mode?

### ISSUE THREAD

**Issue by kurtextrem** [CaliAlec/ChromeIGStory#24]
The code I see doesn't really justify a permanent background page as there is no on-going stream and an event background page would open if instagram.com is opened or if the content script sends a message.

**Comment by CaliAlec** [comment]
@kurtextrem The background page is persistent so React Chrome Redux (https://github.com/tshaddix/react-chrome-redux/) can persist the Redux Store.

I can look into saving the state to the local storage instead of using a persistent background page as mentioned here: https://github.com/tshaddix/react-chrome-redux/issues/8
