### ISSUE TITLE
Not working ig storys

### ISSUE THREAD

**Issue by vrgomes** [CaliAlec/ChromeIGStory#45]
Looks like that today 9-8-2017 it stopped working. Is anyone else also having issues?

Greetings

**Comment by arleitiss** [comment]
This just got fixed, there seems to be no commits so I can only assume it was fb/instagram that messed up something on their end? 

Still kind of curious what caused the issue.

**Comment by CaliAlec** [comment]
@arleitiss It was fixed in https://github.com/CaliAlec/ChromeIGStory/commit/e7843f50b31f20cef265076044bfb28931515e31 because Intagram changed the class names of the DOM elements I was using to inject the stories. Going forward, I need to implement a way to inject the stories without relying on a hardcoded class name.
